---
  - name: Add python3.6 PPA
    apt_repository: repo="ppa:deadsnakes/ppa" state=present
 
  - name: Install python3.6
    apt: name="python3.6" state="present"

  - name: Install python3.6-venv
    apt: name="python3.6-venv" state="present"
    
  - name: upgrade pip3
    pip:
      name: pip
      executable: pip3
      state: latest
