---
  - name: Add python3.6 PPA
    apt_repository: repo="ppa:deadsnakes/ppa" state=present
 
  - name: Install python3.6 and 3.7
    apt: name="{{ item }}" state="present"
    with_items:
      - python3.6
      - python3.6-venv
      - python3.6-wheel
      - python3.6-pip
      - python3.7
      - python3.7-venv
      - python3.7-wheel
      - python3.7-pip
